<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Dr. Sergei G. Sokolovski - Expert in Biophotonics, Medical Spectroscopy, Diagnostics, and Biomedical Device Development.">
    <title>Dr. Sergei G. Sokolovski | Biophotonics Expert</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }
        header {
            background-color: #4CAF50;
            color: white;
            padding: 1em 0;
            text-align: center;
        }
        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }
        section {
            padding: 20px;
            margin: 20px 0;
        }
        h2 {
            color: #4CAF50;
        }
        img {
            width: 100%;
            height: auto;
        }
        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px 0;
            margin-top: 20px;
        }
        .social-links {
            list-style: none;
            padding: 0;
        }
        .social-links li {
            display: inline;
            margin-right: 10px;
        }
        .social-links a {
            color: white;
            text-decoration: none;
        }
    </style>
</head>
<body>

<header>
    <div class="container">
        <h1>Dr. Sergei G. Sokolovski</h1>
        <p>Biophotonics, Medical Spectroscopy, and Diagnostics Expert</p>
    </div>
</header>

<section class="container">
    <h2>About Me</h2>
    <p>I have over 28 years of experience in the interdisciplinary fields of biophotonics, photobiology, and medical spectroscopy, focusing on diagnostics and the development of photonic devices. My work has contributed significantly to advancements in the treatment of cancer, cardiovascular diseases, and tissue engineering.</p>
    <p>Currently, I serve as a Senior Research Fellow at the Aston Institute of Photonic Technologies, where I lead groundbreaking projects involving 3D tissue laser printing and non-invasive diagnostic technologies.</p>
</section>

<section class="container">
    <h2>Projects</h2>
    <ul>
        <li><strong>GlioLighT (2024-2027):</strong> EU H2023 EIC Pathfinder Program (€2.2 million)</li>
        <li><strong>BETTER (2023-2027):</strong> Distributed Health-Data Analytics Research Platform (€10 million)</li>
        <li><strong>PLATFORMA (2020-2022):</strong> Peripheral Nervous System Tissue Engineering (€1.7 million)</li>
        <!-- Add more projects here -->
    </ul>
</section>

<section class="container">
    <h2>Contact</h2>
    <p><strong>Email:</strong> <a href="mailto:s.sokolovsky@aston.ac.uk">s.sokolovsky@aston.ac.uk</a></p>
    <p><strong>Phone:</strong> +44 (0)121 2043542</p>
    <p><strong>Address:</strong> Optoelectronics and Biomedical Photonics Group, Aston University, Birmingham, UK</p>
</section>

<section class="container">
    <h2>Follow Me</h2>
    <ul class="social-links">
        <li><a href="https://www.linkedin.com/in/sergei-sokolovski">LinkedIn</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">ResearchGate</a></li>
        <!-- Add more social links as needed -->
    </ul>
</section>

<footer>
    <p>&copy; 2024 Dr. Sergei G. Sokolovski | All Rights Reserved</p>
</footer>

</body>
</html>
      
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          # Automatically inject router.base in your Nuxt configuration file and set
          # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: nuxt
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - name: Static HTML export with Nuxt
        run: ${{ steps.detect-package-manager.outputs.manager }} run generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
